### ISSUE TITLE
Проблема с освобождением портов при запуске odpm

### ISSUE THREAD

**Issue by wiwiw-wiwiw** [aayartsev/odpm#18]
### **Проблема с освобождением портов при запуске odpm**  

**Описание проблемы:**  
При запуске **odpm** он **некорректно останавливает контейнеры**:  
- Он **останавливает мой контейнер Odoo**, работающий на порту **10018**, хотя не должен этого делать.  
- Контейнер **PostgreSQL (из `docker-compose`) не останавливается**, хотя занимает стандартный порт `5432`. Вместо этого `odpm` запускает новый контейнер PostgreSQL на другом порту (возможно, это ожидаемое поведение, но хотелось бы уточнить).  

**Шаги для воспроизведения:**  
1. Запускаю Odoo и PostgreSQL через `docker-compose` с указанными портами:  
   ```yaml
   services:
     db:
       image: postgres:17
       user: root
       environment:
         - POSTGRES_USER=odoo
         - POSTGRES_PASSWORD=odoo18@2024
         - POSTGRES_DB=postgres
       restart: always
       volumes:
         - ./postgresql:/var/lib/postgresql/data

     odoo18:
       image: odoo:18
       user: root
       depends_on:
         - db
       ports:
         - "10018:8069"
         - "20018:8072" # live chat
       tty: true
       environment:
         - HOST=db
         - USER=odoo
         - PASSWORD=odoo18@2024
       volumes:
         - ./addons:/mnt/extra-addons
         - ./etc:/etc/odoo
       restart: always
   ```
2. Проверяю запущенные контейнеры (`docker ps`):  
   ```
   CONTAINER ID   IMAGE         COMMAND                  STATUS          PORTS
   e2ada1d76da0   odoo:18       "/entrypoint.sh --"      Up 9 seconds    0.0.0.0:10018->8069/tcp, 0.0.0.0:20018->8072/tcp
   d45e8ccb4f13   postgres:17   "docker-entrypoint.s…"   Up 10 seconds   5432/tcp
   ```
3. Запускаю `odpm`, и он:
   - **Останавливает мой контейнер Odoo (10018:8069), хотя не должен этого делать**.
   - **Не останавливает контейнер PostgreSQL (5432)**, но вместо этого **запускает новый экземпляр PostgreSQL на другом порту**.

**Ожидаемое поведение:**  
- `odpm` **не должен останавливать контейнер Odoo**, если он уже работает на порту `10018`.  
- Если PostgreSQL уже работает и занимает порт `5432`, `odpm` **должен корректно его остановить** перед запуском нового контейнера (если это ожидаемое поведение).  

**Фактическое поведение:**  
- `odpm` останавливает **мой Odoo-контейнер (10018:8069)**, хотя Odoo в `odpm` должен запускаться на `8069`
- `odpm` **не останавливает PostgreSQL (5432)** и запускает новый контейнер PostgreSQL **на другом порту**.  

**Дополнительная информация:**  
- ОС: LMDE6
- Версия `odpm`: 3.0-beta
- Версия Docker: version 27.5.1, build 9f9e405
- Версия Odoo: 18  
- Версия PostgreSQL: 17
